name: hurricane_events
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  email_validator: ^2.1.17
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  google_sign_in: ^6.1.5
  grouped_list: ^5.1.2
  image_picker: ^0.8.6+1
  intl: ^0.18.1
  provider: ^6.0.5
  retrofit: ^4.0.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  talker_dio_logger: ^2.3.0
  timeago: ^3.5.0
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/icons/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
